ScheduleApp/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScheduleApp.Data;
using ScheduleApp.Models;
using ScheduleApp.Constants;

namespace ScheduleApp.Controllers
{
    [Authorize(Roles = "Адміністратор")]
    public class GroupController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GroupController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Group
        public async Task<IActionResult> Index()
        {
            return View(await _context.Groups.ToListAsync());
        }

        // GET: Group/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Group/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Group/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupId,Name")] Group group)
        {
            if (ModelState.IsValid)
            {
                var existedGroup = await _context.Groups
               .FirstOrDefaultAsync(m => m.Name == group.Name);

                if (existedGroup == null)
                {
                    _context.Add(group);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData[ScheduleConstants.ERROR_MESSAGE_KEY] = ScheduleConstants.ERROR_MESSAGE_PREFIX + "Додати саме цю назву групи неможливо. Група з цим номером/назвою вже існує!";

                }
            }
            return View(group);
        }

        // GET: Group/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        // POST: Group/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupId,Name")] Group @group)
        {
            if (id != @group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                    var existedGroup = await _context.Groups
                    .FirstOrDefaultAsync(m => m.Name == group.Name);
                if (existedGroup == null)
                {
                    try
                    {
                        _context.Update(@group);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!GroupExists(group.GroupId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData[ScheduleConstants.ERROR_MESSAGE_KEY] = ScheduleConstants.ERROR_MESSAGE_PREFIX + "Змінити назву групи неможливо. Група з цим номером/назвою вже існує!";
                }
              
            }
            return View(@group);
        }

        // GET: Group/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Group/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Groups.FindAsync(id);
            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.GroupId == id);
        }
    }
}

ScheduleApp/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ScheduleApp.Models;
using ScheduleApp.ViewModels;

namespace ScheduleApp.Controllers
{
    [Authorize(Roles = "Адміністратор")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

ScheduleApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScheduleApp.Data;
using ScheduleApp.Models;
using ScheduleApp.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ScheduleApp.Controllers
{
    [Authorize(Roles = "Адміністратор")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public UserController(ApplicationDbContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            return View(await _context.CustomUsers.Include(u => u.Group).ToListAsync());
        }

        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "Name");
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id","Email","FirstName","LastName","GroupId")]User userForm)
        {
            if (id != userForm.Id)
            {
                return NotFound();
            }

            User user = await _userManager.FindByIdAsync(id);
            user.Email = userForm.Email;
            user.UserName = userForm.Email;
            user.FirstName = userForm.FirstName;
            user.LastName = userForm.LastName;
            user.GroupId = userForm.GroupId;

            if (ModelState.IsValid)
            {
                try
                {
                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "Name");
            return View(user);
        }

        public IActionResult Register()
        {
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email, FirstName = model.FirstName, LastName = model.LastName, GroupId = model.GroupId };
                // добавляем пользователя
                var result = await _userManager.CreateAsync(user, model.Password);                
                if (result.Succeeded)
                {
                    // установка куки
                    //await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("Manage", "Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "Name");
            return View(model);
        }

        // GET: User/Delete/5
        [Authorize(Roles = "Адміністратор")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(l => l.Group)
                .Include(l => l.Lessons)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Адміністратор")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        private bool UserExists(string id)
        {
            return _context.CustomUsers.Any(e => e.Id == id);
        }


    }
}

ScheduleApp/Views/Home/Index.cshtml
@model IEnumerable<ScheduleApp.Models.Lesson>
@{
    ViewData["Title"] = "Home Page";
}
<h1 class="text-center">Welcome</h1>

ScheduleApp/Views/Home/Manage.cshtml
@{
    ViewData["Title"] = "Manage";
}

    <div class="text-center">
        <h1 class="display-4">Admin page</h1>
        <a class="btn btn-outline-dark btn-lg btn-block" asp-controller="User" asp-action="Index">Manage users</a>
        <a class="btn btn-outline-dark btn-lg btn-block" asp-controller="Role" asp-action="Index">Manage roles</a>
        <a class="btn btn-outline-dark btn-lg btn-block" asp-controller="Lesson" asp-action="Index">Manage lessons</a>
        <a class="btn btn-outline-dark btn-lg btn-block" asp-controller="Subject" asp-action="Index">Manage subjects</a>
        <a class="btn btn-outline-dark btn-lg btn-block" asp-controller="Group" asp-action="Index">Manage groups</a>
        <a class="btn btn-outline-dark btn-lg btn-block" asp-controller="Classroom" asp-action="Index">Manage classrooms</a>
    </div>

ScheduleApp/Views/Home/StudentHome.cshtml
@model IEnumerable<ScheduleApp.Models.Lesson>
@{
    ViewData["Title"] = "Student Page";
    DateTime filterDate = ViewBag.FilterDate;
}
<partial name="ErrorMessage" model="ViewBag.ErrorMessage" />

<div class="text-center">
    <h1 class="display-4">Розклад</h1>
    <div class="row">
        <div class="input-group mb-3 col-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">День</span>
            </div>
            <input onchange="reloadWithNewDate(this)" type="date"
                   asp-for="@filterDate" class="form-control"
                   aria-label="Default" aria-describedby="inputGroup-sizing-default"
                   placeholder="@filterDate">
        </div>
    </div>
    <table class="table table-hover">
        <thead class="thead-light">
            <tr>                
                    <th scope="col">
                        Номер пари
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.StartLesson)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.EndLesson)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Subject)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Classroom)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Teacher)
                    </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

            <tr onclick="location.href = '../Lesson/Details/@item.LessonId'; return false">
                    <th scope="row">
                        @Html.DisplayFor(modelItem => item.Number)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartLesson)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndLesson)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Classroom.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Teacher.FullName)
                    </td>
            </tr>
           }
        </tbody>
    </table>
</div>
<script>
    function reloadWithNewDate(dateInput) {
        var value = dateInput.value;
        location.href = '@Url.Action("StudentHome", "Home")?date=' + value;
    }
</script>

ScheduleApp/Views/Home/TeacherHome.cshtml
@model IEnumerable<ScheduleApp.Models.Lesson>
@{
    ViewData["Title"] = "TeacherHome";
    DateTime filterDate = ViewBag.FilterDate;
    int filter = ViewBag.FilterOption;
}
<div class="text-center">
    <div class="row">
        <div class="input-group mb-3 col-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-default">День</span>
            </div>
            <input onchange="reloadWithNewDate(this)" type="date"
                   asp-for="@filterDate" class="form-control"
                   aria-label="Default" aria-describedby="inputGroup-sizing-default"
                   placeholder="@filterDate">
        </div>
    </div>
    <div class="btn-group btn-group-toggle mb-3" data-toggle="buttons">
        <label class="btn btn-secondary @(filter == 1 ? "active" : "")">
            <input onchange="check()" type="radio" name="options" id="workingDays" 
                   autocomplete="off" @(filter == 1 ? "checked" : "")> Робочі дні
        </label>
        <label class="btn btn-secondary @(filter == 2 ? "active" : "")">
            <input onchange="check()" type="radio" name="options" id="withWeekends" 
                   autocomplete="off" @(filter == 2 ? "checked" : "")> З вихідними
        </label>
        <label class="btn btn-secondary @(filter == 3 ? "active" : "")">
            <input onchange="check()" type="radio" name="options" id="allDays" 
                   autocomplete="off" @(filter == 3 ? "checked" : "")> Всі дні
        </label>
    </div>
    <div id="scrolling_div" class="list-inline" style="overflow-x:auto; white-space:nowrap">
        <div class="list-inline-item w-5" style="position:sticky; left:0; z-index:10">
            <div class="list-group list-group-flush">
                <label class="list-group-item list-group-item-info border border-info mb-1">
                    День та час
                </label>
                @foreach (var item in ViewBag.NumbersList)
                {
                    <div class="list-group-item">
                        <div>@item</div>
                    </div>
                }
            </div>
        </div>
        @foreach (var date in ViewBag.DatesList)
        {
            var lessonNum = 0;
            var lessonsAbsent = !Model.Any(l => l.Date == date);
            var weekend = (date.DayOfWeek == DayOfWeek.Saturday || date.DayOfWeek == DayOfWeek.Sunday);
            <div @(date == filterDate ? "id=activeBlock ":"")
                 class="list-inline-item @(lessonsAbsent?"lessonsAbsent":"") @(weekend?"weekend":"")"
                 @(filter == 1 ? lessonsAbsent || weekend ? "hidden" : "" : "")
                 @(filter == 2 ? lessonsAbsent ? "hidden" : "" : "")>
                <div class="list-group">
                    <label class="list-group-item @(date == filterDate ? "active":"") list-group-item-success mb-1">
                        @date.ToShortDateString()
                    </label>
                    @foreach (var item in Model.Where(l => l.Date == date).OrderBy(l => l.Number))
                    {
                        @if (item.Number > lessonNum)
                        {
                            @for (var i = lessonNum; i < item.Number; i++)
                            {
                                <div class="list-group-item btn btn-outline-warning">
                                    <div>Вікно</div>
                                </div>
                                lessonNum++;
                            }
                        }
                        <div class="list-group-item btn btn-outline-info"
                             onclick="window.location.href='@Url.Action("Details","Lesson")/@item.LessonId'">
                            @if (item.Date.DayOfWeek == date.DayOfWeek)
                            {
                                <div>
                                    @Html.DisplayFor(modelItem => item.Subject.Name)
                                    каб.@Html.DisplayFor(modelItem => item.Classroom.Name)
                                    @Html.DisplayFor(modelItem => item.Group.Name)
                                </div>
                            }
                        </div>
                        lessonNum++;
                    }
                </div>
            </div>
        }
    </div>
</div>
<script>
    window.onload = function exampleFunction() {
        document.getElementById("activeBlock").scrollIntoView();
    }

    var lessonsAbsent = document.getElementsByClassName("lessonsAbsent");
    var weekends = document.getElementsByClassName("weekend");

    function reloadWithNewDate(dateInput) {
        var filter;
        if (document.getElementById("workingDays").checked == true) {
            filter = 1;
        }
        if (document.getElementById("withWeekends").checked == true) {
            filter = 2;
        }
        if (document.getElementById("allDays").checked == true) {
            filter = 3;
        }

        var value = dateInput.value;
        location.href = '@Url.Action("TeacherHome", "Home")?newDate=' + value + '&filter=' + filter;
    }

    function check() {
        if (document.getElementById("workingDays").checked == true) {
            for(var i=0; i<lessonsAbsent.length; i++) lessonsAbsent[i].hidden = true;
            for(var i=0; i<weekends.length; i++) weekends[i].hidden = true;
        }
        if (document.getElementById("withWeekends").checked == true) {
            for (var i = 0; i < weekends.length; i++) weekends[i].hidden = false;
            for(var i=0; i<lessonsAbsent.length; i++) lessonsAbsent[i].hidden = true;
        }
        if (document.getElementById("allDays").checked == true) {
            for(var i=0; i<lessonsAbsent.length; i++) lessonsAbsent[i].hidden = false;
            for(var i=0; i<weekends.length; i++) weekends[i].style.hidden = false;
        }
    }
</script>